import { createFileRoute, Link } from "@tanstack/react-router";
import { Brand, Icon, PageShell } from "../components/streambox";
import heroImage from "../assets/last-signal-hero.jpg";
export const Route = createFileRoute("/login")({
  head: () => ({ meta: [
    { title: "Sign In — StreamBox" }, { name: "description", content: "Static sign-in interface for the fictional StreamBox streaming experience." },
    { property: "og:title", content: "Sign In — StreamBox" }, { property: "og:description", content: "Static sign-in interface for the fictional StreamBox streaming experience." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: LoginPage,
});
function LoginPage() { return <PageShell bare><div className="relative grid min-h-screen place-items-center overflow-hidden px-5 py-12"><img src={heroImage} alt="" width={1920} height={1080} className="absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-login-overlay" /><div className="relative w-full max-w-md rounded-md border border-border bg-surface/85 p-6 shadow-poster backdrop-blur-xl sm:p-9"><Brand /><div className="mt-10"><p className="text-xs font-bold uppercase text-primary">Welcome back</p><h1 className="mt-2 font-display text-4xl font-black">Sign in to StreamBox</h1><p className="mt-3 text-sm text-muted-foreground">Your watchlist is waiting.</p></div><form className="mt-8 space-y-5"><label className="block text-xs font-semibold text-muted-foreground">Email address<input type="email" placeholder="name@example.com" className="mt-2 h-12 w-full rounded-md border border-border bg-card px-4 text-sm text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-ring" /></label><label className="block text-xs font-semibold text-muted-foreground">Password<input type="password" placeholder="Enter your password" className="mt-2 h-12 w-full rounded-md border border-border bg-card px-4 text-sm text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-ring" /></label><div className="flex items-center justify-between gap-4 text-xs"><label className="flex items-center gap-2 text-muted-foreground"><input type="checkbox" className="h-4 w-4 accent-primary" /> Remember me</label><a href="#forgot" className="font-semibold text-foreground hover:text-primary">Forgot password?</a></div><button type="submit" className="flex h-12 w-full items-center justify-center gap-2 rounded-md bg-primary text-sm font-bold text-primary-foreground shadow-brand transition hover:bg-primary-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Icon name="play" className="h-4 w-4 fill-current" /> Sign in</button></form><p className="mt-7 text-center text-sm text-muted-foreground">New to StreamBox? <a href="#create" className="font-bold text-foreground hover:text-primary">Create an account</a></p><Link to="/" className="mt-5 block text-center text-xs text-muted-foreground hover:text-foreground">Back to browsing</Link></div></div></PageShell>; }
