import { createFileRoute } from "@tanstack/react-router";
import { ActionLink, Icon, MediaRow, PageShell, titles } from "../components/streambox";
import heroImage from "../assets/last-signal-hero.jpg";

export const Route = createFileRoute("/movie-details")({
  head: () => ({ meta: [
    { title: "The Last Signal — StreamBox" }, { name: "description", content: "Explore The Last Signal, an original fictional science-fiction mystery on StreamBox." },
    { property: "og:title", content: "The Last Signal — StreamBox" }, { property: "og:description", content: "Explore The Last Signal, an original fictional science-fiction mystery on StreamBox." },
    { property: "og:type", content: "video.movie" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: DetailsPage,
});

function DetailsPage() {
  return <PageShell><section className="relative min-h-[48rem] overflow-hidden pt-16"><img src={heroImage} alt="The Last Signal radio telescope under a mysterious transmission" width={1920} height={1080} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-detail-overlay" /><div className="relative mx-auto grid min-h-[48rem] max-w-screen-2xl items-end gap-8 px-5 pb-14 pt-32 sm:px-8 md:grid-cols-[14rem_minmax(0,1fr)] lg:px-10"><img src={heroImage} alt="The Last Signal poster crop" width={768} height={1152} className="hidden aspect-[2/3] w-full rounded-md border border-border object-cover shadow-poster md:block" /><div className="max-w-3xl"><p className="text-xs font-bold uppercase text-primary">A StreamBox Original Film</p><h1 className="mt-2 font-display text-5xl font-black sm:text-7xl">The Last Signal</h1><div className="mt-5 flex flex-wrap items-center gap-3 text-sm font-semibold text-muted-foreground"><span className="flex items-center gap-1 text-score"><Icon name="star" className="h-4 w-4 fill-current" /> 9.1</span><span>2026</span><span>2h 18m</span><span>Sci-Fi • Mystery • Drama</span></div><p className="mt-6 max-w-2xl text-base leading-7 text-foreground/80">When isolated radio astronomer Mara Voss decodes a transmission from beyond our solar system, she uncovers a warning sent across centuries. With governments closing in and time running out, Mara must decide whether the message is humanity's salvation—or its final invitation.</p><div className="mt-7 flex flex-wrap gap-3"><ActionLink to="/player" icon="play">Watch now</ActionLink><ActionLink to="/player" icon="play" secondary>Play trailer</ActionLink><ActionLink to="/profile" icon="plus" secondary>My list</ActionLink></div><dl className="mt-8 grid max-w-xl grid-cols-2 gap-x-6 gap-y-3 text-sm"><div><dt className="text-muted-foreground">Director</dt><dd className="mt-1 font-semibold">Elena Vey</dd></div><div><dt className="text-muted-foreground">Language</dt><dd className="mt-1 font-semibold">English</dd></div><div><dt className="text-muted-foreground">Cast</dt><dd className="mt-1 font-semibold">Amara Reed, Leon Vale, Idris North</dd></div><div><dt className="text-muted-foreground">Audio</dt><dd className="mt-1 font-semibold">Dolby Atmos • 5.1</dd></div></dl></div></div></section><div className="mx-auto max-w-screen-2xl px-5 py-8 sm:px-8 lg:px-10"><MediaRow title="More like this" items={titles.slice(1, 8)} /></div></PageShell>;
}
