import { createFileRoute, Link } from "@tanstack/react-router";
import { Icon, PageShell } from "../components/streambox";
import heroImage from "../assets/last-signal-hero.jpg";
export const Route = createFileRoute("/player")({
  head: () => ({ meta: [
    { title: "Now Playing: The Last Signal — StreamBox" }, { name: "description", content: "Static cinematic player interface for The Last Signal on StreamBox." },
    { property: "og:title", content: "Now Playing: The Last Signal — StreamBox" }, { property: "og:description", content: "Static cinematic player interface for The Last Signal on StreamBox." },
    { property: "og:type", content: "video.movie" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: PlayerPage,
});
function PlayerPage() { return <PageShell bare><main className="relative min-h-screen overflow-hidden bg-background"><img src={heroImage} alt="The Last Signal paused at the radio telescope scene" width={1920} height={1080} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-player-overlay" /><header className="absolute inset-x-0 top-0 z-10 grid grid-cols-[auto_minmax(0,1fr)] items-center gap-4 p-5 sm:p-8"><Link to="/movie-details" aria-label="Back to movie details" className="grid h-10 w-10 place-items-center rounded-full bg-background/45 text-foreground backdrop-blur-md"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="h-5 w-5"><path d="m15 18-6-6 6-6" /></svg></Link><div className="min-w-0"><p className="truncate text-sm font-bold sm:text-base">The Last Signal</p><p className="truncate text-xs text-muted-foreground">StreamBox Original • 2026</p></div></header><div className="absolute inset-0 grid place-items-center"><span className="grid h-20 w-20 place-items-center rounded-full border border-foreground/20 bg-primary text-primary-foreground shadow-brand backdrop-blur-md sm:h-24 sm:w-24"><Icon name="play" className="h-9 w-9 fill-current sm:h-11 sm:w-11" /></span></div><div className="absolute inset-x-0 bottom-0 z-10 p-5 sm:p-8"><div className="mb-4 flex items-center justify-between text-xs font-semibold text-foreground"><span>42:18</span><span>2:18:06</span></div><div className="relative h-1.5 rounded-full bg-foreground/25"><div className="h-full w-[31%] rounded-full bg-primary"><span className="absolute left-[31%] top-1/2 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary" /></div></div><div className="mt-6 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4"><div className="flex min-w-0 items-center gap-2 sm:gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-foreground text-background"><Icon name="play" className="h-4 w-4 fill-current" /></span><span className="hidden sm:block"><Icon name="volume" /></span><div className="hidden h-1 w-24 rounded-full bg-foreground/30 sm:block"><div className="h-full w-2/3 rounded-full bg-foreground" /></div></div><div className="flex shrink-0 items-center gap-1 sm:gap-3"><span className="rounded-sm border border-foreground/20 bg-background/40 px-2.5 py-1.5 text-[11px] font-bold backdrop-blur-md">1x</span><span className="rounded-sm border border-foreground/20 bg-background/40 px-2.5 py-1.5 text-[11px] font-bold backdrop-blur-md">4K</span><span className="grid h-9 w-9 place-items-center"><Icon name="subtitles" /></span><span className="grid h-9 w-9 place-items-center"><Icon name="settings" /></span><span className="grid h-9 w-9 place-items-center"><Icon name="expand" /></span></div></div></div></main></PageShell>; }
