import { createFileRoute } from "@tanstack/react-router";
import { Icon, MediaRow, PageShell, titles } from "../components/streambox";
export const Route = createFileRoute("/profile")({
  head: () => ({ meta: [
    { title: "My Profile & List — StreamBox" }, { name: "description", content: "View a fictional StreamBox profile, saved titles, favorites, and watch history." },
    { property: "og:title", content: "My Profile & List — StreamBox" }, { property: "og:description", content: "View a fictional StreamBox profile, saved titles, favorites, and watch history." },
    { property: "og:type", content: "profile" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: ProfilePage,
});
function ProfilePage() { const progress = titles.slice(0, 5).map((item, i) => ({...item, progress: [41, 75, 28, 90, 55][i]})); return <PageShell><section className="border-b border-border bg-surface pt-28"><div className="mx-auto max-w-screen-2xl px-5 pb-10 sm:px-8 lg:px-10"><div className="grid grid-cols-[auto_minmax(0,1fr)] items-center gap-5"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-md border border-border bg-profile text-2xl font-black shadow-brand">AR</div><div className="min-w-0"><p className="text-xs font-bold uppercase text-primary">Primary profile</p><h1 className="mt-1 truncate font-display text-3xl font-black sm:text-5xl">Alex Rivera</h1><p className="mt-2 text-sm text-muted-foreground">Film explorer • Member since 2024</p></div></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["plus","My List","18 titles"],["clock","Continue","5 titles"],["history","History","42 watched"],["heart","Favorites","12 titles"]].map(([icon,label,value]) => <div key={label} className="rounded-md border border-border bg-card p-4"><Icon name={icon as "plus"} className="h-5 w-5 text-primary" /><p className="mt-3 text-sm font-bold">{label}</p><p className="mt-1 text-xs text-muted-foreground">{value}</p></div>)}</div></div></section><div className="mx-auto max-w-screen-2xl px-5 py-8 sm:px-8 lg:px-10"><MediaRow title="Continue watching" items={progress} landscape /><MediaRow title="My list" items={titles.slice(1, 8)} /><MediaRow title="Favorite movies" items={[...titles].reverse().slice(0, 7)} /><MediaRow title="Watch history" items={titles.slice(3, 10)} /></div></PageShell>; }
