import { createFileRoute } from "@tanstack/react-router";
import { Filters, Icon, MovieCard, PageShell, titles } from "../components/streambox";
export const Route = createFileRoute("/search")({
  head: () => ({ meta: [
    { title: "Search Movies & Shows — StreamBox" }, { name: "description", content: "Search the fictional StreamBox catalog by title, genre, year, or rating." },
    { property: "og:title", content: "Search Movies & Shows — StreamBox" }, { property: "og:description", content: "Search the fictional StreamBox catalog by title, genre, year, or rating." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: SearchPage,
});
function SearchPage() { return <PageShell><div className="mx-auto min-h-screen max-w-screen-2xl px-5 pb-16 pt-28 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase text-primary">Find your next story</p><h1 className="mt-2 font-display text-4xl font-black sm:text-6xl">Search StreamBox</h1><label className="mt-8 grid max-w-3xl grid-cols-[auto_minmax(0,1fr)] items-center gap-3 rounded-md border border-border bg-card px-4 focus-within:border-primary"><Icon name="search" className="h-6 w-6 text-muted-foreground" /><input type="search" placeholder="Titles, people, genres" aria-label="Search StreamBox" className="h-14 min-w-0 bg-transparent text-base text-foreground outline-none placeholder:text-muted-foreground" /></label><div className="mt-6"><Filters /></div><div className="mt-5 flex flex-wrap gap-2 text-xs text-muted-foreground"><span className="font-semibold text-foreground">Year:</span>{["2026", "2025", "2024", "Earlier"].map(x => <span key={x} className="rounded-sm border border-border bg-card px-3 py-1.5">{x}</span>)}<span className="ml-3 font-semibold text-foreground">Rating:</span>{["9+", "8+", "7+"].map(x => <span key={x} className="rounded-sm border border-border bg-card px-3 py-1.5">{x}</span>)}</div><h2 className="mt-12 font-display text-2xl font-bold">Popular searches</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">{titles.map((item) => <MovieCard key={item.title} item={item} />)}</div></div></PageShell>; }
