/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MovieDetailsRouteImport } from './routes/movie-details'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TvShowsRouteImport } from './routes/tv-shows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieDetailsRoute = MovieDetailsRouteImport.update({
  id: '/movie-details',
  path: '/movie-details',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TvShowsRoute = TvShowsRouteImport.update({
  id: '/tv-shows',
  path: '/tv-shows',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movie-details': typeof MovieDetailsRoute
  '/movies': typeof MoviesRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/tv-shows': typeof TvShowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movie-details': typeof MovieDetailsRoute
  '/movies': typeof MoviesRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/tv-shows': typeof TvShowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movie-details': typeof MovieDetailsRoute
  '/movies': typeof MoviesRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/tv-shows': typeof TvShowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/movie-details'
    | '/movies'
    | '/player'
    | '/profile'
    | '/search'
    | '/tv-shows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/movie-details'
    | '/movies'
    | '/player'
    | '/profile'
    | '/search'
    | '/tv-shows'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/movie-details'
    | '/movies'
    | '/player'
    | '/profile'
    | '/search'
    | '/tv-shows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MovieDetailsRoute: typeof MovieDetailsRoute
  MoviesRoute: typeof MoviesRoute
  PlayerRoute: typeof PlayerRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  TvShowsRoute: typeof TvShowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie-details': {
      id: '/movie-details'
      path: '/movie-details'
      fullPath: '/movie-details'
      preLoaderRoute: typeof MovieDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-shows': {
      id: '/tv-shows'
      path: '/tv-shows'
      fullPath: '/tv-shows'
      preLoaderRoute: typeof TvShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MovieDetailsRoute: MovieDetailsRoute,
  MoviesRoute: MoviesRoute,
  PlayerRoute: PlayerRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  TvShowsRoute: TvShowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
